name: yuwen

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sql@2024
      - MYSQL_DATABASE=yuwen
      - MYSQL_USER=yuwen
      - MYSQL_PASSWORD=sql@2024
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - yuwen-net

  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - DATABASE_URL=mysql+pymysql://yuwen:sql@2024@mysql:3306/yuwen
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      - yuwen-net

volumes:
  mysql_data:

networks:
  yuwen-net:
    driver: bridge 