name: yuwen

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: yuwen
      MYSQL_USER: yuwen
      MYSQL_PASSWORD: sql2024
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --default-time-zone='+8:00'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://yuwen:sql2024@mysql:3306/yuwen
      - TZ=Asia/Shanghai
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: 